# Generated by Django 4.2.3 on 2023-07-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecomback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('inStock', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('VETEMENT', 'Vet'), ('CHAUSSURE', 'Chaus')], max_length=10)),
            ],
        ),
    ]
